http://localhost:9200
POST /etpgpb_ru_application-development-products/_search?pretty
{
  "query":{
    "bool":{
      "must":[]
    }
  },
  "sort": [
    {
      "sort_name":
      {"order":"asc"}
    }
  ]
}
